language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
before_script:
- git config --global user.email "aruizca@gmail.com"
- git config --global user.name "Angel Ruiz"
script:
- gradle publish -Dorg.ajoberstar.grgit.auth.username=${GH_USERNAME} -Dorg.ajoberstar.grgit.auth.password=${GH_PASSWORD} --stacktrace --info
env:
  global:
    secure: tHGX6vdvDCYyH/ztj4Pl4otp2GekrtY6+0anv612FcOPvubGqJd47aOxl4b78sVAAC6kYfWi2G1Dy6OvWK38WMYIyz8JP2U/qElBot2WA4DBhatlqU2u+fg52a0DmVx1JkLP/VG+LTBNluRYt10Vbqw/XbuO1+fmv8q2OTfxWA4=
