language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
before_script:
- git config --global user.email "aruizca@gmail.com"
- git config --global user.name "aruizca"
script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- gradle publish --stacktrace --info
env:
  global:
    secure: R7sqzyyixVt3kpxS68yEnE9Bt/D8HcCDNrT8Svc7u5nwgnOjBVIU4LbVyHtvejLQ/wKQDu0eS2u+YiLURaoOTf1DROA4dA8pkYl7U2Un1V0ue5schN32NI7A7Tep7BVK2tPJKptbGmWcI7duK9nJfM6XJFU1IxYr3KGelnQL3Tk=
