= Documentation
:jbake-type: documentation
:jbake-tags: projects, jlangdetect, deck2pdf, teamcity, jbake, groovy
:jbake-status: published


== What is it?

*AjaxAnywhere* is an *Open Source* Java Ajax framework that enables the
developer to **add Ajax behaviour to your web application adding simple
markup and without any Javascript coding**. This library is a fork of
the ancient and abandoned
http://ajaxanywhere.sourceforge.net/[AjaxAnywhere] library hosted in
SourceForge but with the following improvements:

* *The developer does not need to write any Javascript code.* You just
need to include the AjaxAnywhere Javascript file in your page and it
will do the rest for you!!
* AjaxAnywhere Javascript file now *relies on jQuery* to implement all
the required features.
* Code base has been simplified and a dependency with the Java SE HTML
parser has been removed.
* JSF support has been dropped. +

AjaxAnywhere continues to be a *page or page fragment oriented
framework* and not a component framework. So don’t expect to find ``yet
another autocomplete component''.

You can see didactic working
**http://www.ajaxanywhere.com/action/examples[EXAMPLES HERE]**.

== How does it work?

The idea is really simple:

1.  Mark the zones to refresh in you JSP template.
2.  Add special `aa-refresh-zones` on all action trigger elements that
you want to "ajaxify" like: forms, submit buttons, input images or
even normal links.
3.  You can develop your server code as if you were implementing the
classic "synchronous" approach.
4.  AjaxAnywhere servlet filter will intercept the Ajax request and
extract the content that needs to be refreshed from the response. The
"refresh zones" contents will be put in XML back to the client +
5.  AjaxAnywhere Javascript is responsible for parsing the XML and
inserting the content in the page.

The following picture and diagram may help to visualize it:

[.float-group]
--
[.left.thumbnail-next]
image::http://nerderg.com/media/show/1537[alt="\"Ajaxified\" form with AjaxAnywhere", 410, class="thumbnail", caption="Figure 1 - ", title="\"Ajaxified\" form with AjaxAnywhere", class="thumbnail"]

[.left.thumbnail-next]
image::http://nerderg.com/media/show/1555[alt="AjaxAnywhere request life cycle", 380, caption="Figure 2 - ", title="AjaxAnywhere request life cycle"]
--

== Usage
=== So, how do you "ajaxify" page elements with AjaxAnywhere?

Just add a new attribute called *aa-refresh-zones,* with a comma
separated list of names of the *zones* you want to refresh, to any
**form**, **input**, **button**,*select* or **anchor element**.

* **<form …>**: this will automatically ``ajaxify'' all the submits from
within the form
(http://www.ajaxanywhere.com/action/examples#example1[working example]):


